option('wayfire_shadows', type: 'boolean', value: 'false', description: 'Install wayfire-shadows plugin')
option('focus_request', type: 'boolean', value: 'false', description: 'Install wayfire focus-request plugin')
option('pixdecor', type: 'boolean', value: 'false', description: 'Install wayfire pixdecor plugin')
option('filters', type: 'boolean', value: 'false', description: 'Install wayfire filters plugin')
